# Generated by Django 3.1.4 on 2020-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20201207_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_issue',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='Completion_date',
            field=models.DateTimeField(),
        ),
    ]
