# Generated by Django 3.1.2 on 2020-10-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Colour', models.CharField(max_length=30)),
                ('state_number', models.CharField(db_column='state number', max_length=3)),
                ('Car_type', models.CharField(choices=[('A', 'Motorcycle'), ('B', 'car'), ('C', 'truck'), ('D', 'bus')], db_column='Car type', max_length=1)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first name', max_length=30)),
                ('last_name', models.CharField(db_column='last name', max_length=30)),
                ('birthday', models.DateTimeField()),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ownership_day', models.DateTimeField()),
                ('OW_Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fat_Ape.car')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fat_Ape.driver')),
            ],
            options={
                'db_table': 'Ownership',
            },
        ),
        migrations.CreateModel(
            name='driver_license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('Date_issue', models.DateTimeField()),
                ('driver_type', models.CharField(choices=[('A', 'Motorcycle'), ('B', 'car'), ('C', 'truck'), ('D', 'bus')], max_length=1)),
                ('driver_license_driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fat_Ape.driver')),
            ],
            options={
                'db_table': 'driver license',
            },
        ),
    ]
